dist: xenial
sudo: false
language: go
go:
- '1.11'
before_script:
- wget https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
- export PROTOC_DIR=/tmp/proto
- mkdir -p $PROTOC_DIR
- unzip protoc-3.6.1-linux-x86_64.zip -d $PROTOC_DIR
- chmod +x $PROTOC_DIR/bin/protoc
- export PATH=$PATH:/tmp/proto/bin
- go get -u github.com/onsi/ginkgo/ginkgo
- go get -u github.com/onsi/gomega/...
- export GO111MODULE=on


before_deploy:
  - rm protoc-gen-state
  - export VER=`echo $TRAVIS_TAG|tr -d v`
  - GOOS=darwin GOARCH=amd64 go build ./ && zip protoc-gen-state state/options.proto protoc-gen-state-$VER-$GOOS-x86_64.zip
  - GOOS=linux GOARCH=amd64 go build ./ && zip protoc-gen-state state/options.proto protoc-gen-state-$VER-$GOOS-x86_64.zip
  - GOOS=windows GOARCH=amd64 go build ./ && zip protoc-gen-state state/options.proto protoc-gen-state-$VER-$GOOS-x86_64.zip
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "idk"
  file_glob: true
  file:
    - protoc-gen-state-*.zip
  on:
  tags: true

